# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'YTPanGesture' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for YTPanGesture
pod 'SDCycleScrollView', '~> 1.73'
pod 'Masonry', '~> 1.1.0'
  target 'YTPanGestureTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'YTPanGestureUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
